### ISSUE TITLE
Old Video Poster Not Being Removed When Episode Number Changes

### ISSUE THREAD

**Issue by Selkie707** [ZeroQI/YouTube-Agent.bundle#17]
Agent works great, been migrating a youtube library over to plex and noticed some oddities with the posters on episodes. Description and everything else is correct.

My guess is that as more episodes are added and episode number changes the poster from what used to be that episode is kept. The new poster is downloaded and available for selection, it is just not set as the default one every time.

What Poster section Looks Like(The right poster is "Net Neutrality" but another videos is selected:
![image](https://user-images.githubusercontent.com/18093341/45310735-2117df80-b4f5-11e8-9bca-8f581314cb18.png)

Logs;
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2367528/com.plexapp.agents.youtube.log)

[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2367526/com.plexapp.agents.youtube.log)

**Comment by ZeroQI** [comment]
Which is why a playlist id is better, as the épisode number is forces by the scanner.
What happen on a metadata update on that sériés?

**Comment by Selkie707** [comment]
Refreshing metadata does not change the poster or remove any bad ones.
I want to do playlists but most of the channels I want to backup do not have playlists for everything.

**Comment by Selkie707** [comment]
A solution to this temporarily seems to be deleting the library, cleaning bundles, then re-adding the library.

When a new episode is added it will probably change the episode number though and could cause it again.

Not sure if there is a way for an agent to force the use of the just downloaded image over the ones plex has in cache or clearing the episode cache but that would fix the problem permanently.

**Comment by Selkie707** [comment]
The picture issue seems to still be occurring.
I deleted, cleaned bundles, and recreated the library then started downloading more videos to be sure.
One thing i did notice is that while downloading/adding videos it would sometimes show an episode twice, same poster, same name, etc. The get info would show that they were definitely distinct videos.

Logs:
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2368066/com.plexapp.agents.youtube.log)
[com.plexapp.system.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2368067/com.plexapp.system.log)
[Cody'sLab.scanner.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2368069/Cody.sLab.scanner.log)

**Comment by Selkie707** [comment]
If you want to test it on your end my youtube-dl stuff:
[https://drive.google.com/file/d/1H2TepQ8wDnd9IY2w0-B0Wllx5-L9EMmV/view](https://drive.google.com/file/d/1H2TepQ8wDnd9IY2w0-B0Wllx5-L9EMmV/view)

I have all that directly in the folder that plex scans for the youtube series library and youtube-dl runs there.

**Comment by ZeroQI** [comment]
@Selkie707 please test new version and report. had cleaned fist ep screenshot used as p[oster, not the ep itself, should be solved now

**Comment by Selkie707** [comment]
@ZeroQI 

Okay after ~300 episodes as a test I can confirm that the issue still persists. After looking over a few episodes it would seem that there are less bad posters. Now there is a single bad poster, then two correct posters. One being the one downloaded from you-tube, the other good one being the auto generated one.

If you want the logs I can provide them as well.

![image](https://user-images.githubusercontent.com/18093341/45381397-36fbd200-b5d3-11e8-8016-4ebdc3254d40.png)

**Comment by ZeroQI** [comment]
Please

**Comment by Selkie707** [comment]
sorry for the delay.
Logs:
[_root_-YouTube.scanner.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372960/_root_-YouTube.scanner.log)
[com.plexapp.agents.youtube.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372961/com.plexapp.agents.youtube.log)
[com.plexapp.agents.youtube1.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372962/com.plexapp.agents.youtube1.log)
[com.plexapp.agents.youtube2.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372963/com.plexapp.agents.youtube2.log)
[Cody'sLab.filelist.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372964/Cody.sLab.filelist.log)
[Cody'sLab.scanner.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372965/Cody.sLab.scanner.log)
[_root_-YouTube.filelist.log](https://github.com/ZeroQI/YouTube-Agent.bundle/files/2372966/_root_-YouTube.filelist.log)

**Comment by Selkie707** [comment]
Episode 570 matched as "Year of BeeKeeping Episode 41.2, Grantsville hive update"
The actual file however is 20130105 Chicken Thinks its a Dog [ihuxNw7EnB4].mkv

Episdode 549 does not appear in the library. Episode 349 is the right match for the file currently showing up as episode 570.

After refreshing the metadata all the metadata fixed itself besides the posters. For example Episode 470 now correctly identifies as Chicken Thinks its a Dog [ihuxNw7EnB4] however it still has the poster for Year of BeeKeeping Episode 41.2, Grantsville hive update

**Comment by ZeroQI** [comment]
if an episode jumped from one episode number to another, plex will not update and correct the metadata, only when doing a full refresh. It seems the active original poster will stay, a plex issue.
I honestly cannot do much.
You should really use playlist if they exist, as the episode numbering will not change over time

**Comment by GlassedSilver** [comment]
Can't we generate a fantasy EP number from information like upload date and the first n numerals in the file's md5 hash?

Unless of course this would probably trigger Plex to believe it's an extra/special, right?

Man, if Plex just supported letters in the episode ID there'd be a lot of things we could fix...

Youtube and anime truly are Plex' kryptonite. A software that seems incredibly easy to use and work on as long as you stay in Hollywood becomes a nightmare once you throw your niche needs at it...

Has anything changed about the situation by the way that you could workaround for that you couldn't before? I'd love to make it all work a little nicer... :(
